// Generated by gencpp from file altitude_controller/Error.msg
// DO NOT EDIT!


#ifndef ALTITUDE_CONTROLLER_MESSAGE_ERROR_H
#define ALTITUDE_CONTROLLER_MESSAGE_ERROR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace altitude_controller
{
template <class ContainerAllocator>
struct Error_
{
  typedef Error_<ContainerAllocator> Type;

  Error_()
    : errorX(0.0)
    , errorY(0.0)
    , errorT(0.0)
    , errorZ(0.0)  {
    }
  Error_(const ContainerAllocator& _alloc)
    : errorX(0.0)
    , errorY(0.0)
    , errorT(0.0)
    , errorZ(0.0)  {
  (void)_alloc;
    }



   typedef float _errorX_type;
  _errorX_type errorX;

   typedef float _errorY_type;
  _errorY_type errorY;

   typedef float _errorT_type;
  _errorT_type errorT;

   typedef float _errorZ_type;
  _errorZ_type errorZ;





  typedef boost::shared_ptr< ::altitude_controller::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::altitude_controller::Error_<ContainerAllocator> const> ConstPtr;

}; // struct Error_

typedef ::altitude_controller::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::altitude_controller::Error > ErrorPtr;
typedef boost::shared_ptr< ::altitude_controller::Error const> ErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::altitude_controller::Error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::altitude_controller::Error_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::altitude_controller::Error_<ContainerAllocator1> & lhs, const ::altitude_controller::Error_<ContainerAllocator2> & rhs)
{
  return lhs.errorX == rhs.errorX &&
    lhs.errorY == rhs.errorY &&
    lhs.errorT == rhs.errorT &&
    lhs.errorZ == rhs.errorZ;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::altitude_controller::Error_<ContainerAllocator1> & lhs, const ::altitude_controller::Error_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace altitude_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::altitude_controller::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::altitude_controller::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::altitude_controller::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::altitude_controller::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::altitude_controller::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::altitude_controller::Error_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::altitude_controller::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02b23bb72f5cb40fc5320fa3bb6465eb";
  }

  static const char* value(const ::altitude_controller::Error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02b23bb72f5cb40fULL;
  static const uint64_t static_value2 = 0xc5320fa3bb6465ebULL;
};

template<class ContainerAllocator>
struct DataType< ::altitude_controller::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "altitude_controller/Error";
  }

  static const char* value(const ::altitude_controller::Error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::altitude_controller::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 errorX\n"
"float32 errorY\n"
"float32 errorT\n"
"float32 errorZ\n"
"\n"
"\n"
;
  }

  static const char* value(const ::altitude_controller::Error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::altitude_controller::Error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.errorX);
      stream.next(m.errorY);
      stream.next(m.errorT);
      stream.next(m.errorZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::altitude_controller::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::altitude_controller::Error_<ContainerAllocator>& v)
  {
    s << indent << "errorX: ";
    Printer<float>::stream(s, indent + "  ", v.errorX);
    s << indent << "errorY: ";
    Printer<float>::stream(s, indent + "  ", v.errorY);
    s << indent << "errorT: ";
    Printer<float>::stream(s, indent + "  ", v.errorT);
    s << indent << "errorZ: ";
    Printer<float>::stream(s, indent + "  ", v.errorZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALTITUDE_CONTROLLER_MESSAGE_ERROR_H
