// Generated by gencpp from file mavros_off_board/TriggerRequest.msg
// DO NOT EDIT!


#ifndef MAVROS_OFF_BOARD_MESSAGE_TRIGGERREQUEST_H
#define MAVROS_OFF_BOARD_MESSAGE_TRIGGERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_off_board
{
template <class ContainerAllocator>
struct TriggerRequest_
{
  typedef TriggerRequest_<ContainerAllocator> Type;

  TriggerRequest_()
    : trigger(false)  {
    }
  TriggerRequest_(const ContainerAllocator& _alloc)
    : trigger(false)  {
  (void)_alloc;
    }



   typedef uint8_t _trigger_type;
  _trigger_type trigger;





  typedef boost::shared_ptr< ::mavros_off_board::TriggerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_off_board::TriggerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerRequest_

typedef ::mavros_off_board::TriggerRequest_<std::allocator<void> > TriggerRequest;

typedef boost::shared_ptr< ::mavros_off_board::TriggerRequest > TriggerRequestPtr;
typedef boost::shared_ptr< ::mavros_off_board::TriggerRequest const> TriggerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_off_board::TriggerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_off_board::TriggerRequest_<ContainerAllocator1> & lhs, const ::mavros_off_board::TriggerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.trigger == rhs.trigger;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_off_board::TriggerRequest_<ContainerAllocator1> & lhs, const ::mavros_off_board::TriggerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_off_board

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_off_board::TriggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_off_board::TriggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_off_board::TriggerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6d1152a533bdef9ec687318c8e489b0";
  }

  static const char* value(const ::mavros_off_board::TriggerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6d1152a533bdef9ULL;
  static const uint64_t static_value2 = 0xec687318c8e489b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_off_board/TriggerRequest";
  }

  static const char* value(const ::mavros_off_board::TriggerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool trigger\n"
;
  }

  static const char* value(const ::mavros_off_board::TriggerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trigger);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_off_board::TriggerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_off_board::TriggerRequest_<ContainerAllocator>& v)
  {
    s << indent << "trigger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_OFF_BOARD_MESSAGE_TRIGGERREQUEST_H
