// Generated by gencpp from file mavros_off_board/Trigger.msg
// DO NOT EDIT!


#ifndef MAVROS_OFF_BOARD_MESSAGE_TRIGGER_H
#define MAVROS_OFF_BOARD_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <mavros_off_board/TriggerRequest.h>
#include <mavros_off_board/TriggerResponse.h>


namespace mavros_off_board
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace mavros_off_board


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_off_board::Trigger > {
  static const char* value()
  {
    return "1531357144714babf83a2def976015d9";
  }

  static const char* value(const ::mavros_off_board::Trigger&) { return value(); }
};

template<>
struct DataType< ::mavros_off_board::Trigger > {
  static const char* value()
  {
    return "mavros_off_board/Trigger";
  }

  static const char* value(const ::mavros_off_board::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_off_board::TriggerRequest> should match
// service_traits::MD5Sum< ::mavros_off_board::Trigger >
template<>
struct MD5Sum< ::mavros_off_board::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_off_board::Trigger >::value();
  }
  static const char* value(const ::mavros_off_board::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_off_board::TriggerRequest> should match
// service_traits::DataType< ::mavros_off_board::Trigger >
template<>
struct DataType< ::mavros_off_board::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_off_board::Trigger >::value();
  }
  static const char* value(const ::mavros_off_board::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_off_board::TriggerResponse> should match
// service_traits::MD5Sum< ::mavros_off_board::Trigger >
template<>
struct MD5Sum< ::mavros_off_board::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_off_board::Trigger >::value();
  }
  static const char* value(const ::mavros_off_board::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_off_board::TriggerResponse> should match
// service_traits::DataType< ::mavros_off_board::Trigger >
template<>
struct DataType< ::mavros_off_board::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_off_board::Trigger >::value();
  }
  static const char* value(const ::mavros_off_board::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_OFF_BOARD_MESSAGE_TRIGGER_H
