// Generated by gencpp from file drone_controller/controllerResponse.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_CONTROLLERRESPONSE_H
#define DRONE_CONTROLLER_MESSAGE_CONTROLLERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_controller
{
template <class ContainerAllocator>
struct controllerResponse_
{
  typedef controllerResponse_<ContainerAllocator> Type;

  controllerResponse_()
    : success(false)  {
    }
  controllerResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::drone_controller::controllerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_controller::controllerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct controllerResponse_

typedef ::drone_controller::controllerResponse_<std::allocator<void> > controllerResponse;

typedef boost::shared_ptr< ::drone_controller::controllerResponse > controllerResponsePtr;
typedef boost::shared_ptr< ::drone_controller::controllerResponse const> controllerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_controller::controllerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_controller::controllerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_controller::controllerResponse_<ContainerAllocator1> & lhs, const ::drone_controller::controllerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_controller::controllerResponse_<ContainerAllocator1> & lhs, const ::drone_controller::controllerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_controller::controllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::controllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::controllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::controllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::controllerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::controllerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_controller::controllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::drone_controller::controllerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_controller::controllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_controller/controllerResponse";
  }

  static const char* value(const ::drone_controller::controllerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_controller::controllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success  # Indicate if the operation was successful\n"
;
  }

  static const char* value(const ::drone_controller::controllerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_controller::controllerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct controllerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_controller::controllerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_controller::controllerResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_CONTROLLERRESPONSE_H
