// Generated by gencpp from file drone_controller/Information.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_INFORMATION_H
#define DRONE_CONTROLLER_MESSAGE_INFORMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_controller
{
template <class ContainerAllocator>
struct Information_
{
  typedef Information_<ContainerAllocator> Type;

  Information_()
    : information()  {
    }
  Information_(const ContainerAllocator& _alloc)
    : information(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _information_type;
  _information_type information;





  typedef boost::shared_ptr< ::drone_controller::Information_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_controller::Information_<ContainerAllocator> const> ConstPtr;

}; // struct Information_

typedef ::drone_controller::Information_<std::allocator<void> > Information;

typedef boost::shared_ptr< ::drone_controller::Information > InformationPtr;
typedef boost::shared_ptr< ::drone_controller::Information const> InformationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_controller::Information_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_controller::Information_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_controller::Information_<ContainerAllocator1> & lhs, const ::drone_controller::Information_<ContainerAllocator2> & rhs)
{
  return lhs.information == rhs.information;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_controller::Information_<ContainerAllocator1> & lhs, const ::drone_controller::Information_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_controller::Information_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::Information_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::Information_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::Information_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::Information_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::Information_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_controller::Information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f643f4492d5df4a7264b4dfdbe3626f";
  }

  static const char* value(const ::drone_controller::Information_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f643f4492d5df4aULL;
  static const uint64_t static_value2 = 0x7264b4dfdbe3626fULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_controller::Information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_controller/Information";
  }

  static const char* value(const ::drone_controller::Information_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_controller::Information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string information\n"
;
  }

  static const char* value(const ::drone_controller::Information_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_controller::Information_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.information);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Information_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_controller::Information_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_controller::Information_<ContainerAllocator>& v)
  {
    s << indent << "information: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.information);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_INFORMATION_H
